"""Alert and AlertEvidence SQLAlchemy Models.

Provides persistent data models for security detections generated by the
deterministic detection engine, with immutable evidence links to the
originating SecurityEvent records.
"""

import uuid
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional
from sqlalchemy import (
    Column,
    String,
    DateTime,
    Text,
    ForeignKey,
    Index,
    UniqueConstraint,
    JSON,
)
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import Mapped, mapped_column, relationship
from backend.app.db.base import Base


class Alert(Base):
    """Security alert generated deterministically by detection rules."""

    __tablename__ = "alerts"

    # Primary identifier: UUID v4
    id: Mapped[str] = mapped_column(
        String(36),
        primary_key=True,
        default=lambda: str(uuid.uuid4()),
        index=True,
        doc="Unique UUID identifier for the alert",
    )

    # Rule identification
    rule_id: Mapped[str] = mapped_column(
        String(64),
        nullable=False,
        index=True,
        doc="Detection rule identifier (e.g., RULE-001)",
    )

    rule_name: Mapped[str] = mapped_column(
        String(128),
        nullable=False,
        doc="Human-readable rule name",
    )

    # Alert narrative and classification
    title: Mapped[str] = mapped_column(
        String(255),
        nullable=False,
        doc="Brief summary title of the detected activity",
    )

    description: Mapped[str] = mapped_column(
        Text,
        nullable=False,
        doc="Detailed explanation of the alert and trigger criteria",
    )

    severity: Mapped[str] = mapped_column(
        String(32),
        nullable=False,
        index=True,
        doc="Standardized severity: low, medium, high, critical",
    )

    status: Mapped[str] = mapped_column(
        String(32),
        nullable=False,
        default="new",
        index=True,
        doc="Triage status: new, in_review, dismissed, escalated",
    )

    # Deterministic Deduplication Key
    dedup_key: Mapped[str] = mapped_column(
        String(255),
        nullable=False,
        unique=True,
        index=True,
        doc="Deterministic hash or signature preventing duplicate alerts across detection runs",
    )

    # Affected entity context (indexed for fast analytical lookup)
    affected_user: Mapped[Optional[str]] = mapped_column(
        String(128),
        nullable=True,
        index=True,
        doc="User account targeted or associated with the alert",
    )

    affected_ip: Mapped[Optional[str]] = mapped_column(
        String(45),
        nullable=True,
        index=True,
        doc="Source or target IP address associated with the alert",
    )

    affected_hostname: Mapped[Optional[str]] = mapped_column(
        String(128),
        nullable=True,
        index=True,
        doc="Hostname or cloud resource affected",
    )

    # Timestamps
    detected_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        index=True,
        doc="UTC timestamp when the detected condition occurred in telemetry",
    )

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.now(timezone.utc),
        nullable=False,
        index=True,
        doc="UTC timestamp when the alert record was created by the engine",
    )

    # Phase 4 Forward-Compatibility: Correlation container ID
    incident_id: Mapped[Optional[str]] = mapped_column(
        String(36),
        nullable=True,
        index=True,
        doc="Incident ID if correlated in Phase 4",
    )

    # Contextual metadata (rule parameters, threshold metrics, match details)
    alert_metadata: Mapped[Optional[Dict[str, Any]]] = mapped_column(
        JSON().with_variant(JSONB(), "postgresql"),
        nullable=True,
        default=dict,
        doc="Supplemental rule execution metrics and context",
    )

    # Evidence association
    evidence: Mapped[List["AlertEvidence"]] = relationship(
        "AlertEvidence",
        back_populates="alert",
        cascade="all, delete-orphan",
        order_by="AlertEvidence.created_at",
    )

    # Multi-column indexes for fast SOC queue filtering
    __table_args__ = (
        Index("ix_alerts_severity_status", "severity", "status"),
        Index("ix_alerts_rule_detected", "rule_id", "detected_at"),
        Index("ix_alerts_user_detected", "affected_user", "detected_at"),
    )

    def to_dict(self, include_evidence: bool = False) -> Dict[str, Any]:
        """Serialize alert to dictionary."""
        data: Dict[str, Any] = {
            "id": self.id,
            "rule_id": self.rule_id,
            "rule_name": self.rule_name,
            "title": self.title,
            "description": self.description,
            "severity": self.severity,
            "status": self.status,
            "dedup_key": self.dedup_key,
            "affected_user": self.affected_user,
            "affected_ip": self.affected_ip,
            "affected_hostname": self.affected_hostname,
            "detected_at": self.detected_at.isoformat() if self.detected_at else None,
            "created_at": self.created_at.isoformat() if self.created_at else None,
            "incident_id": self.incident_id,
            "metadata": self.alert_metadata or {},
            "evidence_count": len(self.evidence) if self.evidence else 0,
        }
        if include_evidence:
            data["evidence"] = [e.to_dict() for e in self.evidence]
        return data


class AlertEvidence(Base):
    """Immutable association binding an Alert to its supporting SecurityEvent."""

    __tablename__ = "alert_evidence"

    id: Mapped[str] = mapped_column(
        String(36),
        primary_key=True,
        default=lambda: str(uuid.uuid4()),
        index=True,
        doc="Unique UUID for this evidence record",
    )

    alert_id: Mapped[str] = mapped_column(
        String(36),
        ForeignKey("alerts.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
        doc="Foreign key to the parent Alert",
    )

    event_id: Mapped[str] = mapped_column(
        String(36),
        ForeignKey("security_events.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
        doc="Foreign key to the supporting SecurityEvent",
    )

    evidence_role: Mapped[str] = mapped_column(
        String(64),
        nullable=False,
        default="trigger",
        doc="Functional role in detection: trigger, preceding_failure, successful_login, privilege_escalation, indicator_match",
    )

    description: Mapped[Optional[str]] = mapped_column(
        Text,
        nullable=True,
        doc="Human-readable context explaining why this event is evidence",
    )

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.now(timezone.utc),
        nullable=False,
        doc="UTC timestamp when evidence link was established",
    )

    # Relationships
    alert: Mapped["Alert"] = relationship("Alert", back_populates="evidence")
    event: Mapped["backend.app.models.event.SecurityEvent"] = relationship(
        "backend.app.models.event.SecurityEvent"
    )

    __table_args__ = (
        UniqueConstraint("alert_id", "event_id", name="uq_alert_event_evidence"),
        Index("ix_alert_evidence_alert_event", "alert_id", "event_id"),
    )

    def to_dict(self, include_event: bool = True) -> Dict[str, Any]:
        """Serialize evidence link to dictionary."""
        data: Dict[str, Any] = {
            "id": self.id,
            "alert_id": self.alert_id,
            "event_id": self.event_id,
            "evidence_role": self.evidence_role,
            "description": self.description,
            "created_at": self.created_at.isoformat() if self.created_at else None,
        }
        if include_event and self.event:
            data["event"] = self.event.to_dict()
        return data
